package com.liferay.events.global.mobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EventContact service. Represents a row in the &quot;Matcher_EventContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.events.global.mobile.model.impl.EventContactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.events.global.mobile.model.impl.EventContactImpl}.
 * </p>
 *
 * @author James Falkner
 * @see EventContact
 * @see com.liferay.events.global.mobile.model.impl.EventContactImpl
 * @see com.liferay.events.global.mobile.model.impl.EventContactModelImpl
 * @generated
 */
public interface EventContactModel extends BaseModel<EventContact>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a event contact model instance should use the {@link EventContact} interface instead.
     */

    /**
     * Returns the primary key of this event contact.
     *
     * @return the primary key of this event contact
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this event contact.
     *
     * @param primaryKey the primary key of this event contact
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the given name of this event contact.
     *
     * @return the given name of this event contact
     */
    @AutoEscape
    public String getGivenName();

    /**
     * Sets the given name of this event contact.
     *
     * @param givenName the given name of this event contact
     */
    public void setGivenName(String givenName);

    /**
     * Returns the full name of this event contact.
     *
     * @return the full name of this event contact
     */
    @AutoEscape
    public String getFullName();

    /**
     * Sets the full name of this event contact.
     *
     * @param fullName the full name of this event contact
     */
    public void setFullName(String fullName);

    /**
     * Returns the email address of this event contact.
     *
     * @return the email address of this event contact
     */
    @AutoEscape
    public String getEmailAddress();

    /**
     * Sets the email address of this event contact.
     *
     * @param emailAddress the email address of this event contact
     */
    public void setEmailAddress(String emailAddress);

    /**
     * Returns the city of this event contact.
     *
     * @return the city of this event contact
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this event contact.
     *
     * @param city the city of this event contact
     */
    public void setCity(String city);

    /**
     * Returns the country of this event contact.
     *
     * @return the country of this event contact
     */
    @AutoEscape
    public String getCountry();

    /**
     * Sets the country of this event contact.
     *
     * @param country the country of this event contact
     */
    public void setCountry(String country);

    /**
     * Returns the lat of this event contact.
     *
     * @return the lat of this event contact
     */
    public double getLat();

    /**
     * Sets the lat of this event contact.
     *
     * @param lat the lat of this event contact
     */
    public void setLat(double lat);

    /**
     * Returns the lng of this event contact.
     *
     * @return the lng of this event contact
     */
    public double getLng();

    /**
     * Sets the lng of this event contact.
     *
     * @param lng the lng of this event contact
     */
    public void setLng(double lng);

    /**
     * Returns the job title of this event contact.
     *
     * @return the job title of this event contact
     */
    @AutoEscape
    public String getJobTitle();

    /**
     * Sets the job title of this event contact.
     *
     * @param jobTitle the job title of this event contact
     */
    public void setJobTitle(String jobTitle);

    /**
     * Returns the company of this event contact.
     *
     * @return the company of this event contact
     */
    @AutoEscape
    public String getCompany();

    /**
     * Sets the company of this event contact.
     *
     * @param company the company of this event contact
     */
    public void setCompany(String company);

    /**
     * Returns the industry of this event contact.
     *
     * @return the industry of this event contact
     */
    @AutoEscape
    public String getIndustry();

    /**
     * Sets the industry of this event contact.
     *
     * @param industry the industry of this event contact
     */
    public void setIndustry(String industry);

    /**
     * Returns the interests of this event contact.
     *
     * @return the interests of this event contact
     */
    @AutoEscape
    public String getInterests();

    /**
     * Sets the interests of this event contact.
     *
     * @param interests the interests of this event contact
     */
    public void setInterests(String interests);

    /**
     * Returns the desires of this event contact.
     *
     * @return the desires of this event contact
     */
    @AutoEscape
    public String getDesires();

    /**
     * Sets the desires of this event contact.
     *
     * @param desires the desires of this event contact
     */
    public void setDesires(String desires);

    /**
     * Returns the expertise of this event contact.
     *
     * @return the expertise of this event contact
     */
    @AutoEscape
    public String getExpertise();

    /**
     * Sets the expertise of this event contact.
     *
     * @param expertise the expertise of this event contact
     */
    public void setExpertise(String expertise);

    /**
     * Returns the attendee type of this event contact.
     *
     * @return the attendee type of this event contact
     */
    @AutoEscape
    public String getAttendeeType();

    /**
     * Sets the attendee type of this event contact.
     *
     * @param attendeeType the attendee type of this event contact
     */
    public void setAttendeeType(String attendeeType);

    /**
     * Returns the interested IDs of this event contact.
     *
     * @return the interested IDs of this event contact
     */
    @AutoEscape
    public String getInterestedIds();

    /**
     * Sets the interested IDs of this event contact.
     *
     * @param interestedIds the interested IDs of this event contact
     */
    public void setInterestedIds(String interestedIds);

    /**
     * Returns the pic url of this event contact.
     *
     * @return the pic url of this event contact
     */
    @AutoEscape
    public String getPicUrl();

    /**
     * Sets the pic url of this event contact.
     *
     * @param picUrl the pic url of this event contact
     */
    public void setPicUrl(String picUrl);

    /**
     * Returns the event ID of this event contact.
     *
     * @return the event ID of this event contact
     */
    @AutoEscape
    public String getEventId();

    /**
     * Sets the event ID of this event contact.
     *
     * @param eventId the event ID of this event contact
     */
    public void setEventId(String eventId);

    /**
     * Returns the verified of this event contact.
     *
     * @return the verified of this event contact
     */
    public boolean getVerified();

    /**
     * Returns <code>true</code> if this event contact is verified.
     *
     * @return <code>true</code> if this event contact is verified; <code>false</code> otherwise
     */
    public boolean isVerified();

    /**
     * Sets whether this event contact is verified.
     *
     * @param verified the verified of this event contact
     */
    public void setVerified(boolean verified);

    /**
     * Returns the event contact ID of this event contact.
     *
     * @return the event contact ID of this event contact
     */
    public long getEventContactId();

    /**
     * Sets the event contact ID of this event contact.
     *
     * @param eventContactId the event contact ID of this event contact
     */
    public void setEventContactId(long eventContactId);

    /**
     * Returns the group ID of this event contact.
     *
     * @return the group ID of this event contact
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this event contact.
     *
     * @param groupId the group ID of this event contact
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this event contact.
     *
     * @return the company ID of this event contact
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this event contact.
     *
     * @param companyId the company ID of this event contact
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this event contact.
     *
     * @return the user ID of this event contact
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this event contact.
     *
     * @param userId the user ID of this event contact
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this event contact.
     *
     * @return the user uuid of this event contact
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this event contact.
     *
     * @param userUuid the user uuid of this event contact
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this event contact.
     *
     * @return the user name of this event contact
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this event contact.
     *
     * @param userName the user name of this event contact
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this event contact.
     *
     * @return the create date of this event contact
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this event contact.
     *
     * @param createDate the create date of this event contact
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this event contact.
     *
     * @return the modified date of this event contact
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this event contact.
     *
     * @param modifiedDate the modified date of this event contact
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.events.global.mobile.model.EventContact eventContact);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.events.global.mobile.model.EventContact> toCacheModel();

    @Override
    public com.liferay.events.global.mobile.model.EventContact toEscapedModel();

    @Override
    public com.liferay.events.global.mobile.model.EventContact toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
