package com.liferay.events.global.mobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GeoCache service. Represents a row in the &quot;Matcher_GeoCache&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.events.global.mobile.model.impl.GeoCacheModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.events.global.mobile.model.impl.GeoCacheImpl}.
 * </p>
 *
 * @author James Falkner
 * @see GeoCache
 * @see com.liferay.events.global.mobile.model.impl.GeoCacheImpl
 * @see com.liferay.events.global.mobile.model.impl.GeoCacheModelImpl
 * @generated
 */
public interface GeoCacheModel extends BaseModel<GeoCache> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a geo cache model instance should use the {@link GeoCache} interface instead.
     */

    /**
     * Returns the primary key of this geo cache.
     *
     * @return the primary key of this geo cache
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this geo cache.
     *
     * @param primaryKey the primary key of this geo cache
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the address of this geo cache.
     *
     * @return the address of this geo cache
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this geo cache.
     *
     * @param address the address of this geo cache
     */
    public void setAddress(String address);

    /**
     * Returns the lat of this geo cache.
     *
     * @return the lat of this geo cache
     */
    public double getLat();

    /**
     * Sets the lat of this geo cache.
     *
     * @param lat the lat of this geo cache
     */
    public void setLat(double lat);

    /**
     * Returns the lng of this geo cache.
     *
     * @return the lng of this geo cache
     */
    public double getLng();

    /**
     * Sets the lng of this geo cache.
     *
     * @param lng the lng of this geo cache
     */
    public void setLng(double lng);

    /**
     * Returns the geo cache ID of this geo cache.
     *
     * @return the geo cache ID of this geo cache
     */
    public long getGeoCacheId();

    /**
     * Sets the geo cache ID of this geo cache.
     *
     * @param geoCacheId the geo cache ID of this geo cache
     */
    public void setGeoCacheId(long geoCacheId);

    /**
     * Returns the create date of this geo cache.
     *
     * @return the create date of this geo cache
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this geo cache.
     *
     * @param createDate the create date of this geo cache
     */
    public void setCreateDate(Date createDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.events.global.mobile.model.GeoCache geoCache);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.events.global.mobile.model.GeoCache> toCacheModel();

    @Override
    public com.liferay.events.global.mobile.model.GeoCache toEscapedModel();

    @Override
    public com.liferay.events.global.mobile.model.GeoCache toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
