package com.liferay.events.global.mobile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Message service. Represents a row in the &quot;Matcher_Message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.events.global.mobile.model.impl.MessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.events.global.mobile.model.impl.MessageImpl}.
 * </p>
 *
 * @author James Falkner
 * @see Message
 * @see com.liferay.events.global.mobile.model.impl.MessageImpl
 * @see com.liferay.events.global.mobile.model.impl.MessageModelImpl
 * @generated
 */
public interface MessageModel extends BaseModel<Message>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a message model instance should use the {@link Message} interface instead.
     */

    /**
     * Returns the primary key of this message.
     *
     * @return the primary key of this message
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this message.
     *
     * @param primaryKey the primary key of this message
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the from ID of this message.
     *
     * @return the from ID of this message
     */
    public long getFromId();

    /**
     * Sets the from ID of this message.
     *
     * @param fromId the from ID of this message
     */
    public void setFromId(long fromId);

    /**
     * Returns the to ID of this message.
     *
     * @return the to ID of this message
     */
    public long getToId();

    /**
     * Sets the to ID of this message.
     *
     * @param toId the to ID of this message
     */
    public void setToId(long toId);

    /**
     * Returns the content of this message.
     *
     * @return the content of this message
     */
    @AutoEscape
    public String getContent();

    /**
     * Sets the content of this message.
     *
     * @param content the content of this message
     */
    public void setContent(String content);

    /**
     * Returns the read of this message.
     *
     * @return the read of this message
     */
    public boolean getRead();

    /**
     * Returns <code>true</code> if this message is read.
     *
     * @return <code>true</code> if this message is read; <code>false</code> otherwise
     */
    public boolean isRead();

    /**
     * Sets whether this message is read.
     *
     * @param read the read of this message
     */
    public void setRead(boolean read);

    /**
     * Returns the event ID of this message.
     *
     * @return the event ID of this message
     */
    @AutoEscape
    public String getEventId();

    /**
     * Sets the event ID of this message.
     *
     * @param eventId the event ID of this message
     */
    public void setEventId(String eventId);

    /**
     * Returns the message ID of this message.
     *
     * @return the message ID of this message
     */
    public long getMessageId();

    /**
     * Sets the message ID of this message.
     *
     * @param messageId the message ID of this message
     */
    public void setMessageId(long messageId);

    /**
     * Returns the group ID of this message.
     *
     * @return the group ID of this message
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this message.
     *
     * @param groupId the group ID of this message
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this message.
     *
     * @return the company ID of this message
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this message.
     *
     * @param companyId the company ID of this message
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this message.
     *
     * @return the user ID of this message
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this message.
     *
     * @param userId the user ID of this message
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this message.
     *
     * @return the user uuid of this message
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this message.
     *
     * @param userUuid the user uuid of this message
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this message.
     *
     * @return the user name of this message
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this message.
     *
     * @param userName the user name of this message
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this message.
     *
     * @return the create date of this message
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this message.
     *
     * @param createDate the create date of this message
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this message.
     *
     * @return the modified date of this message
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this message.
     *
     * @param modifiedDate the modified date of this message
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.events.global.mobile.model.Message message);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.events.global.mobile.model.Message> toCacheModel();

    @Override
    public com.liferay.events.global.mobile.model.Message toEscapedModel();

    @Override
    public com.liferay.events.global.mobile.model.Message toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
