package com.liferay.events.global.mobile.model.impl;

import com.liferay.events.global.mobile.model.EventContact;
import com.liferay.events.global.mobile.service.EventContactLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EventContact service. Represents a row in the &quot;Matcher_EventContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventContactImpl}.
 * </p>
 *
 * @author James Falkner
 * @see EventContactImpl
 * @see com.liferay.events.global.mobile.model.EventContact
 * @generated
 */
public abstract class EventContactBaseImpl extends EventContactModelImpl
    implements EventContact {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a event contact model instance should use the {@link EventContact} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EventContactLocalServiceUtil.addEventContact(this);
        } else {
            EventContactLocalServiceUtil.updateEventContact(this);
        }
    }
}
