package com.liferay.events.global.mobile.model.impl;

import com.liferay.events.global.mobile.model.EventPollAnswer;
import com.liferay.events.global.mobile.service.EventPollAnswerLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the EventPollAnswer service. Represents a row in the &quot;Matcher_EventPollAnswer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventPollAnswerImpl}.
 * </p>
 *
 * @author James Falkner
 * @see EventPollAnswerImpl
 * @see com.liferay.events.global.mobile.model.EventPollAnswer
 * @generated
 */
public abstract class EventPollAnswerBaseImpl extends EventPollAnswerModelImpl
    implements EventPollAnswer {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a event poll answer model instance should use the {@link EventPollAnswer} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EventPollAnswerLocalServiceUtil.addEventPollAnswer(this);
        } else {
            EventPollAnswerLocalServiceUtil.updateEventPollAnswer(this);
        }
    }
}
