package com.liferay.events.global.mobile.model.impl;

import com.liferay.events.global.mobile.model.GeoCache;
import com.liferay.events.global.mobile.service.GeoCacheLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the GeoCache service. Represents a row in the &quot;Matcher_GeoCache&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GeoCacheImpl}.
 * </p>
 *
 * @author James Falkner
 * @see GeoCacheImpl
 * @see com.liferay.events.global.mobile.model.GeoCache
 * @generated
 */
public abstract class GeoCacheBaseImpl extends GeoCacheModelImpl
    implements GeoCache {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a geo cache model instance should use the {@link GeoCache} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            GeoCacheLocalServiceUtil.addGeoCache(this);
        } else {
            GeoCacheLocalServiceUtil.updateGeoCache(this);
        }
    }
}
